FROM golang:1.20.4

# WORKDIR /app

# COPY go.mod go.sum ./
# COPY ./db/migrations/-seq app/migrations

# RUN go mod download

# # Copy whatever is left
# COPY . .

# RUN go build -o main cmd/main.go

# CMD sh -c 'migrate -database "postgresql://postgres:Test@123@db:5432/postgres?sslmode=disable" -path ./migrations up && /app/main